services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rakso123
      POSTGRES_DB: budgetbuddy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:Rakso123@db:5432/budgetbuddy
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 10 && python setup.py && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
